name: Checkout

on:
  push:
    

jobs:
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before
        run: ls -la
      - name: Checkout
        uses: actions/checkout@v4
