name: Expressions & Context
run-name: "Expressions & Context by ${{ github.actor }} :rocket:"

on: 
  push:
  issues:
  workflow_dispatch:
  
jobs:
  new-job:
    runs-on: ubuntu-latest
    if: contains(fromJSON('["issues", "pull_request"]'), github.event_name)
    steps:
      - name: Run only on some labels
        if: contains(github.event.issue.labels.*.name, 'zalupa')
        run: echo ${{ join(github.event.issue.labels.*.name, ', ')}}
  using-ex-and-con:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Expressions
        id: expressions
        run: |
          echo '${{ toJSON(github) }}'
          echo '${{ toJSON(job) }}'
          echo '${{ toJSON(secrets) }}'
          echo '${{ toJSON(steps) }}'
          echo '${{ toJSON(runner) }}'
          