name: First Workflow 

on: 
  push:

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest 
    steps:
      - name: Echoing a String
        run: echo "Hello World!"
      - name: Multiline
        run: |
          node -v
          npm -v

  parallel-job:
    runs-on: macos-latest
    steps:
      - name: macOs job
        run: |
          git -v

  depend-job:
    needs: parallel-job
    runs-on: windows-latest
    steps:
      - name: echo a String
        run: Write-Output "Windows String"
      - name: Error step
        run: exit 1 

  
