name: Status Check Functions

on:
  push


jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: sleep 20
      - name: Fail-on-purpose
        id: fail
        run: exit 1
      - name: Runs on failure
        if: failure() && steps.Fail-on-purpose.conclusion == 'failure'
        run: echo 'Runs only on failure'
      - name: Always runs
        if: always()
        run: echo 'Always Runs'

  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
      - run: echo Job 2
