name: Workflow commands

on:
    push:
      

jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Setting an error message
        run: echo "::error::Missing semicolon"
      - name: Setting an error message with params
        run: echo "::error title=Error issue,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicolon"
      - name: Setting a debug message with params
        run: echo "::debug title=Error issue,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicolon"
      - name: Setting a warning message with params
        run: echo "::warning title=Error issue,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicolon"
      - name: Setting a notice message with params
        run: echo "::notice title=Error issue,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicolon"